export interface __match{
    IDMATCH:number,
    IDEDITION:number,
    nat_IDJ1:string,
    nat_IDJ2:string,
    prenom_IDJ1 :string, 
    prenom_IDJ2 :string, 
    nom_IDJ1:string,
    nom_IDJ2:string,
    TOUR:number,
    IDJ1:number,
    IDJ2:number,
    Tour:number,
    VAINQ: number,
    set1l:string,
    set1w:string,
    set2l:string,
    set2w:string,
    set3l:string,
    set3w:string,
    set4l:string,
    set4w:string,
    set5l:string,
    set5w:string,
}
